[workspace]
members = [
    "src/dfx",
]

[patch.crates-io.ic-agent]
version = "0.7.0"
git = "https://github.com/dfinity/agent-rs.git"
rev = "8d76e480304c9b80d2cfc4d8747775eae4ae640c"

[patch.crates-io.ic-asset]
version = "0.2.0"
git = "https://github.com/dfinity/agent-rs.git"
rev = "8d76e480304c9b80d2cfc4d8747775eae4ae640c"

[patch.crates-io.ic-identity-hsm]
version = "0.3.4"
git = "https://github.com/dfinity/agent-rs.git"
rev = "8d76e480304c9b80d2cfc4d8747775eae4ae640c"

[patch.crates-io.ic-utils]
version = "0.5.0"
git = "https://github.com/dfinity/agent-rs.git"
rev = "8d76e480304c9b80d2cfc4d8747775eae4ae640c"
