[workspace]
members = [
    "src/dfx",
]

[patch.crates-io.ic-agent]
version = "0.8.0"
git = "https://github.com/dfinity/agent-rs.git"
rev = "2fb4d5c4337c5de4c05cf8f4015cb71925abab7d"

[patch.crates-io.ic-asset]
version = "0.3.0"
git = "https://github.com/dfinity/agent-rs.git"
rev = "2fb4d5c4337c5de4c05cf8f4015cb71925abab7d"

[patch.crates-io.ic-identity-hsm]
version = "0.3.5"
git = "https://github.com/dfinity/agent-rs.git"
rev = "2fb4d5c4337c5de4c05cf8f4015cb71925abab7d"

[patch.crates-io.ic-utils]
version = "0.6.0"
git = "https://github.com/dfinity/agent-rs.git"
rev = "2fb4d5c4337c5de4c05cf8f4015cb71925abab7d"
